#!/bin/sh
HISTFILE=~/.config/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000
export PATH="$HOME/.local/bin":$PATH
eval "$(zoxide init zsh)"

#NNN
export NNN_PLUG='f:finder;o:fzopen;d:diffs;t:nmount;v:imgview'
export NNN_USE_EDITOR=1
