#! /bin/sh

#Polybar
$HOME/.config/polybar/launch.sh --blocks

#autostart
pgrep -x sxhkd > /dev/null || sxhkd &
optimus-manager-qt &
xfce4-power-manager &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
picom -b  --config ~/.config/picom.conf &
numlockx on &
dunst &
nitrogen --restore &

#BSP config
bspc monitor -d I II III IV V VI VII VIII IX X
bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config single_monocle       true
bspc config history_aware_focus  true

# Border Color

bspc config normal_border_color "#44475a"
bspc config active_border_color "#6272a4"
bspc config focused_border_color "#8be9fd"
bspc config presel_feedback_color "#6272a4"

# Resize using super + mouse(1,2,3)
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Brave-browser desktop='^2'
bspc rule -a discord desktop='^4'
bspc rule -a Pcmanfm desktop='^5'
bspc rule -a mpv desktop='^6'
bspc rule -a Screenkey manage=off

#makes fullscreen without Polybar getting in the way
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_eDP)
#removes the default X cursor
xsetroot -cursor_name left_ptr
