#!/bin/sh
noOfMon=$(xrandr | grep -scw 'connected')

if [ "$noOfMon" -eq 2 ]; then
  xrandr --output HDMI-0 --mode 1920x1080 --pos 1920x0 --rotate normal --output eDP-1-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal
  xrandr --output HDMI-0 --mode 1920x1080 --rate 75.00
else
  notify-send " not found" "Please connect your second Monitor"
fi
