#!/usr/bin/env bash

prompt="dmenu -c -l 7 "

uptime=$(uptime -p | sed -e 's/up //g')
wm_name="$(wmctrl -m | awk -F ":" {'print $2'} | head -n 1)"
wm_pid=$(pidof ${wm_name})

shutdown="Shutdown"
reboot="Restart"
lock="Lock"
logout="Logout"
cancel="Cancel"

option="$cancel\n$shutdown\n$reboot\n$lock\n$logout"

select="$(echo -e "$option" | $prompt -p "$uptime")"

case $select in
	"$shutdown")
		shutdown now
		;;
	"$reboot")
		reboot
		;;
	"$lock")
		slock
		;;
	"$logout")
		kill -TERM "$wm_pid"
esac
